Added deploy steps

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -25,7 +25,7 @@ build:
     # A step that executes `npm install` command
     - npm-install
     - script:
-        name: echo python information
+        name: bower install
         code: |
           npm i -g bower
           bower i --config.interactive=false --allow-root
@@ -39,3 +39,39 @@ build:
         code: |
           echo "node version $(node -v) running"
           echo "npm version $(npm -v) running"
+
+deploy:
+  steps:
+    - npm-install
+    - script:
+      name: install superviosr
+      code: npm i -g supervisor
+    - internal/docker-push:
+      username: $DOCKER_USERNAME
+      password: $DOCKER_PASSWORD
+      repository: frishi/rishighanangular-web
+      ports: 8080
+      cmd: /bin/bash -c "cd /pipeline/source && supervisor --watch ./src src/server.js
+      - add-ssh-key:
+          keyname: digitalocean_PUBLIC
+      - add-to-known_hosts:
+          hostname: 165.227.120.45
+    - script:
+        name: pull latest image
+        code: ssh root@165.227.120.45 docker pull frishi/rishighanangular_web:latest
+    - script:
+        name: stop running container
+        code: ssh root@165.227.120.45 docker stop rgapp || echo "failed to stop running container"
+    - script:
+        name: remove stopped container
+        code: ssh root@165.227.120.45 docker rm rgapp || echo "failed to remove stopped container"
+    - script:
+        name: remove image behind stopped container
+        code: ssh root@165.227.120.45 docker rmi -f frishi/rishighanangular_web:current || echo ‘failed to remove image behind stopped container’
+    - script:
+        name: tag newly pulled image
+        code: ssh root@165.227.120.45 docker tag frishi/rishighanangular_web:latest frishi/rishighanangular:current
+    - script:
+        name: run new container
+        code: ssh root@165.227.120.45 docker run -d -p 8080:8080 --name rgapp frishi/rishighanangular_web:current
+
